server:
  port: 80

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    enabled: false
  mvc:
    view:
      static-path-pattern: /**
  resources:
    static-locations: classpath:/views/,classpath:/static/
  #默认启用开发环境配置，开发环境为dev，生产环境为pro
  profiles:
    active: dev

#mybatis配置
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:com.gy.myproject.**.mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.gy.myproject.**.model  # 注意：对应实体类的路径

mybatis-plus:
  mapper-locations: classpath*:com/**/mapping/*.xml
  typeAliasesPackage: com.**.model
  #typeEnumsPackage: com.jxdinfo.hussar.common.constant.enums
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
